sudo: required
services:
  - docker

before_install:
  - docker build -t abdelmoneimnour24/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true abdelmoneimnour24/docker-react npm run test 